# Generated by Django 4.2.6 on 2023-12-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archived',
            fields=[
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='archived_todo', serialize=False, to='apiToDo.todo')),
                ('archived', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
