# Generated by Django 4.2.6 on 2023-12-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiToDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archived',
            old_name='archived',
            new_name='created',
        ),
        migrations.AddField(
            model_name='archived',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
