# Generated by Django 4.2.6 on 2023-12-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiToDo', '0002_rename_archived_archived_created_archived_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archived',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
