# Generated by Django 4.2.6 on 2023-11-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snake_position', models.TextField(default='[(0, 0)]')),
                ('score', models.IntegerField(default=0)),
                ('life', models.IntegerField(default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
